version: '3.3'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - database
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080
    networks:
      - database
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

networks:
  database:
volumes:
  postgres:
  pgadmin4:
